const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/server.js','utf8').replace('CHANGE_THIS_TO_A_LONG_PRIVATE_PASSWORD','Private-test-admin-password-2026');
const rows=new Map();
function api(body,origin='https://mofid-academy.github.io'){
 const sandbox={require,Buffer,$:()=>({first:()=>({json:{body,headers:{origin}}})}),$input:{all:()=>[...rows.entries()].map(([key,value])=>({json:{key,value:JSON.stringify(value)}}))}};
 const [out]=vm.runInNewContext('(function(){'+source+'})()',sandbox);const result=out.json;
 if(result.write)rows.set(result.key,JSON.parse(result.value));
 return JSON.parse(JSON.stringify(result));
}
const call=(token,action,payload={})=>api({token,action,...payload});
assert.equal(call('','courses').status,401);
assert.equal(api({action:'login',username:'admin',password:'Private-test-admin-password-2026'},'https://evil.invalid').status,403);
const admin=api({action:'login',username:'admin',password:'Private-test-admin-password-2026'}).response;
assert.equal(admin.user.role,'admin');assert.equal(admin.token.length,64);
assert.equal(call(admin.token,'createUser',{username:'ali01',name:'علی',organization:'آکادمی',password:'Participant-password-1'}).status,200);
assert.equal(call(admin.token,'createUser',{username:'sara01',name:'سارا',organization:'آکادمی',password:'Participant-password-2'}).status,200);
assert.equal(call(admin.token,'createUser',{username:'ali01',name:'علی',organization:'آکادمی',password:'Duplicate-password'}).status,409);
assert(!JSON.stringify(call(admin.token,'users').response).includes('passwordHash'));
assert(!JSON.stringify([...rows.values()]).includes('Participant-password-1'));
const ali=api({action:'login',username:'ali01',password:'Participant-password-1'}).response;
const sara=api({action:'login',username:'sara01',password:'Participant-password-2'}).response;
for(const action of ['publish','unpublish','users','createUser','updateUser','reports'])assert.equal(call(ali.token,action).status,403,action);
const course={version:1,id:'test-course',title:'دوره آزمایش',description:'',mode:'ai',createdAt:'2026-10-04',sourceName:'source',sources:[{id:'s1',label:'منبع',text:'متن تست'}],modules:[{id:'m1',title:'فصل',questions:[{id:'q1',question:'سؤال آزمایش',options:['۱','۲','۳','۴'],answer:2,explanation:'توضیح',sourceIds:['s1']}],flashcards:[{id:'f1',front:'رو',back:'پشت',sourceIds:['s1']}]}],slides:[{title:'آغاز',bullets:[],notes:'',sourceIds:[]}],progress:{read:['m1'],answers:{q1:3},reviews:{}}};
assert.equal(call(admin.token,'publish',{course}).status,200);
assert.deepEqual(call(ali.token,'courses').response.courses[0].progress,{read:[],answers:{},reviews:{}});
assert.equal(call(ali.token,'progress',{courseId:course.id,progress:{read:['m1','bad'],answers:{q1:2,bad:1},reviews:{f1:{box:1,due:20}}}}).status,200);
assert.equal(call(ali.token,'courses').response.courses[0].progress.answers.q1,2);
assert.deepEqual(call(sara.token,'courses').response.courses[0].progress.answers,{});
assert.equal(call(admin.token,'reports').response.reports[0].correct,1);
assert.equal(call(admin.token,'publish',{course:{...course,title:'changed'}}).status,409);
assert.equal(call(admin.token,'unpublish',{courseId:course.id}).status,200);
assert.equal(call(ali.token,'courses').response.courses.length,0);
assert.equal(call(ali.token,'progress',{courseId:course.id}).status,404);
assert.equal(call(admin.token,'publish',{course}).status,200);
assert.equal(call(admin.token,'updateUser',{username:'ali01',active:false}).status,200);
assert.equal(call(ali.token,'courses').status,401);
assert.equal(call(admin.token,'updateUser',{username:'sara01',password:'New-participant-password'}).status,200);
assert.equal(call(sara.token,'courses').status,401);
for(let i=0;i<5;i++)assert.equal(api({action:'login',username:'random',password:'wrong'}).status,401);
assert.equal(api({action:'login',username:'random',password:'wrong'}).status,429);
assert.equal(call(admin.token,'logout').status,200);assert.equal(call(admin.token,'courses').status,401);
console.log('Passed: login, roles, private password hashes, publication, progress isolation, reports, revocation, reset, logout, rate limit, origin.');
